import { AgentSession, AgentStep } from "@/types"

function makeStep(
  idx: number,
  base: string,
  overrides: Partial<AgentStep> = {}
): AgentStep {
  const defaults: AgentStep = {
    id: `step-${base}-${idx}`,
    stepNumber: idx,
    type: "llm_call",
    status: "success",
    timestamp: new Date(
      new Date(base).getTime() + idx * 4000
    ).toISOString(),
    durationMs: 800 + Math.floor(Math.random() * 2200),
    input: `{"messages": [{"role": "user", "content": "Step ${idx} input: analyze the codebase and identify the issue"}]}`,
    output: `{"role": "assistant", "content": "Step ${idx} analysis complete. Found 3 relevant files. Proceeding with fix."}`,
    tokenUsage: {
      promptTokens: 800 + idx * 120,
      completionTokens: 200 + idx * 40,
      totalTokens: 1000 + idx * 160,
    },
  }
  return { ...defaults, ...overrides }
}

export const MOCK_SESSIONS: AgentSession[] = [
  // ── Session 1: E-commerce product search fix (completed) ──────────────────
  {
    id: "sess-001",
    agentName: "CodeFixAgent",
    projectId: "proj-ecomm",
    projectName: "E-commerce AI",
    taskId: "task-001",
    taskName: "Fix product search ranking",
    startedAt: "2026-04-04T09:00:00Z",
    endedAt: "2026-04-04T09:02:14Z",
    status: "completed",
    totalSteps: 6,
    totalTokens: 12480,
    totalCostUsd: 0.0347,
    steps: [
      makeStep(1, "2026-04-04T09:00:00Z", {
        type: "llm_call",
        input: '{"task": "Analyze product search ranking regression in commit a3f9b"}',
        output: '{"plan": ["Read search.ts", "Check scoring algorithm", "Apply fix"]}',
        tokenUsage: { promptTokens: 650, completionTokens: 180, totalTokens: 830 },
      }),
      makeStep(2, "2026-04-04T09:00:00Z", {
        type: "tool_call",
        toolName: "read_file",
        input: '{"path": "src/search/ranking.ts"}',
        output: '{"content": "export function scoreProduct(p) { return p.rating * 0.6 + p.sales * 0.4 }"}',
        durationMs: 120,
        tokenUsage: undefined,
      }),
      makeStep(3, "2026-04-04T09:00:00Z", {
        type: "llm_call",
        input: '{"context": "scoreProduct uses stale weights", "task": "propose fix"}',
        output: '{"fix": "Update weights to rating*0.4 + sales*0.3 + recency*0.3"}',
        tokenUsage: { promptTokens: 1200, completionTokens: 320, totalTokens: 1520 },
      }),
      makeStep(4, "2026-04-04T09:00:00Z", {
        type: "tool_call",
        toolName: "write_file",
        input: '{"path": "src/search/ranking.ts", "content": "...updated weights..."}',
        output: '{"success": true}',
        durationMs: 80,
        tokenUsage: undefined,
      }),
      makeStep(5, "2026-04-04T09:00:00Z", {
        type: "tool_call",
        toolName: "run_tests",
        input: '{"suite": "search"}',
        output: '{"passed": 12, "failed": 0}',
        durationMs: 3400,
        tokenUsage: undefined,
      }),
      makeStep(6, "2026-04-04T09:00:00Z", {
        type: "llm_call",
        input: '{"test_results": "12 passed", "task": "summarize changes"}',
        output: '{"summary": "Fixed product search ranking. Updated scoring weights to balance rating, sales velocity, and recency. All 12 tests pass."}',
        tokenUsage: { promptTokens: 980, completionTokens: 280, totalTokens: 1260 },
      }),
    ],
  },

  // ── Session 2: Support bot context overflow (failed) ──────────────────────
  {
    id: "sess-002",
    agentName: "SupportBot",
    projectId: "proj-support",
    projectName: "Customer Support Bot",
    taskId: "task-002",
    taskName: "Handle complex refund policy query",
    startedAt: "2026-04-04T09:15:00Z",
    endedAt: "2026-04-04T09:17:32Z",
    status: "failed",
    totalSteps: 5,
    totalTokens: 28600,
    totalCostUsd: 0.1123,
    steps: [
      makeStep(1, "2026-04-04T09:15:00Z", {
        type: "retrieval",
        toolName: "vector_search",
        input: '{"query": "refund policy international orders", "k": 20}',
        output: '{"chunks": [{"text": "Refund policy section 1..."}, {"text": "International shipping terms..."}]}',
        durationMs: 340,
        tokenUsage: undefined,
      }),
      makeStep(2, "2026-04-04T09:15:00Z", {
        type: "retrieval",
        toolName: "vector_search",
        input: '{"query": "customs duties return process exceptions", "k": 20}',
        output: '{"chunks": 20}',
        durationMs: 290,
        tokenUsage: undefined,
      }),
      makeStep(3, "2026-04-04T09:15:00Z", {
        type: "llm_call",
        input: '{"context_length": 24500, "task": "synthesize refund policy answer"}',
        output: '{"partial_answer": "Based on sections 1-4 of the policy..."}',
        tokenUsage: { promptTokens: 18400, completionTokens: 1200, totalTokens: 19600 },
      }),
      makeStep(4, "2026-04-04T09:15:00Z", {
        type: "llm_call",
        input: '{"context_length": 31200, "task": "add exception clauses"}',
        output: "",
        status: "error",
        tokenUsage: { promptTokens: 28600, completionTokens: 0, totalTokens: 28600 },
        error: {
          code: "CONTEXT_OVERFLOW",
          message: "Request exceeds maximum context length: 32768 tokens (got 31200 prompt + requested 4096 completion)",
          stackTrace: "at LLMClient.complete (llm-client.ts:142)\nat SupportBot.synthesize (support-bot.ts:87)",
        },
      }),
      makeStep(5, "2026-04-04T09:15:00Z", {
        type: "observation",
        status: "error",
        input: '{"error": "CONTEXT_OVERFLOW"}',
        output: '{"action": "abort", "reason": "context_length_exceeded"}',
        durationMs: 50,
        tokenUsage: undefined,
        error: {
          code: "SESSION_ABORTED",
          message: "Session aborted due to unrecoverable error in step 4",
        },
      }),
    ],
  },

  // ── Session 3: Research assistant citation extraction (completed) ──────────
  {
    id: "sess-003",
    agentName: "ResearchAgent",
    projectId: "proj-research",
    projectName: "Research Assistant",
    taskId: "task-003",
    taskName: "Extract citations from PDF batch",
    startedAt: "2026-04-04T10:00:00Z",
    endedAt: "2026-04-04T10:04:45Z",
    status: "completed",
    totalSteps: 8,
    totalTokens: 9320,
    totalCostUsd: 0.0284,
    steps: [
      makeStep(1, "2026-04-04T10:00:00Z", {
        type: "tool_call",
        toolName: "list_files",
        input: '{"dir": "papers/", "ext": ".pdf"}',
        output: '{"files": ["arxiv-2401.pdf", "nature-2024.pdf", "icml-2024.pdf"]}',
        durationMs: 60,
        tokenUsage: undefined,
      }),
      makeStep(2, "2026-04-04T10:00:00Z", {
        type: "tool_call",
        toolName: "parse_pdf",
        input: '{"path": "papers/arxiv-2401.pdf"}',
        output: '{"text": "Abstract: We present...", "pages": 12}',
        durationMs: 1200,
        tokenUsage: undefined,
      }),
      makeStep(3, "2026-04-04T10:00:00Z", {
        type: "llm_call",
        input: '{"task": "extract citations from arxiv-2401.pdf", "text_length": 4200}',
        output: '{"citations": [{"authors": "Smith et al.", "year": 2023, "title": "..."}]}',
        tokenUsage: { promptTokens: 1400, completionTokens: 380, totalTokens: 1780 },
      }),
      makeStep(4, "2026-04-04T10:00:00Z", {
        type: "tool_call",
        toolName: "parse_pdf",
        input: '{"path": "papers/nature-2024.pdf"}',
        output: '{"text": "Nature paper content...", "pages": 8}',
        durationMs: 890,
        tokenUsage: undefined,
      }),
      makeStep(5, "2026-04-04T10:00:00Z", {
        type: "llm_call",
        input: '{"task": "extract citations from nature-2024.pdf"}',
        output: '{"citations": [{"authors": "Chen et al.", "year": 2024}]}',
        tokenUsage: { promptTokens: 1100, completionTokens: 290, totalTokens: 1390 },
      }),
      makeStep(6, "2026-04-04T10:00:00Z", {
        type: "tool_call",
        toolName: "parse_pdf",
        input: '{"path": "papers/icml-2024.pdf"}',
        output: '{"text": "ICML paper content...", "pages": 10}',
        durationMs: 1050,
        tokenUsage: undefined,
      }),
      makeStep(7, "2026-04-04T10:00:00Z", {
        type: "llm_call",
        input: '{"task": "extract citations from icml-2024.pdf"}',
        output: '{"citations": [{"authors": "Park & Kim", "year": 2024}]}',
        tokenUsage: { promptTokens: 1320, completionTokens: 340, totalTokens: 1660 },
      }),
      makeStep(8, "2026-04-04T10:00:00Z", {
        type: "llm_call",
        input: '{"task": "deduplicate and format all citations as BibTeX"}',
        output: '{"bibtex": "@article{smith2023...", "total": 47}',
        tokenUsage: { promptTokens: 3200, completionTokens: 1290, totalTokens: 4490 },
      }),
    ],
  },

  // ── Session 4: E-commerce checkout rate limit (failed) ────────────────────
  {
    id: "sess-004",
    agentName: "CodeFixAgent",
    projectId: "proj-ecomm",
    projectName: "E-commerce AI",
    taskId: "task-004",
    taskName: "Optimize checkout API calls",
    startedAt: "2026-04-04T11:00:00Z",
    endedAt: "2026-04-04T11:01:08Z",
    status: "failed",
    totalSteps: 4,
    totalTokens: 4200,
    totalCostUsd: 0.0118,
    steps: [
      makeStep(1, "2026-04-04T11:00:00Z", {
        type: "llm_call",
        input: '{"task": "review checkout.ts API call patterns"}',
        output: '{"finding": "checkout makes 8 sequential API calls that could be parallelized"}',
        tokenUsage: { promptTokens: 900, completionTokens: 240, totalTokens: 1140 },
      }),
      makeStep(2, "2026-04-04T11:00:00Z", {
        type: "tool_call",
        toolName: "call_external_api",
        input: '{"endpoint": "https://payments.internal/v2/validate", "method": "POST"}',
        output: "",
        status: "error",
        durationMs: 30050,
        tokenUsage: undefined,
        error: {
          code: "RATE_LIMIT_EXCEEDED",
          message: "429 Too Many Requests: rate limit exceeded (100 req/min). Retry-After: 60s",
        },
      }),
      makeStep(3, "2026-04-04T11:00:00Z", {
        type: "llm_call",
        input: '{"error": "RATE_LIMIT_EXCEEDED", "task": "handle rate limit"}',
        output: '{"action": "retry_with_backoff", "wait_ms": 60000}',
        status: "error",
        tokenUsage: { promptTokens: 1800, completionTokens: 360, totalTokens: 2160 },
        error: {
          code: "RATE_LIMIT_EXCEEDED",
          message: "Retry also rate limited. Agent halting.",
        },
      }),
      makeStep(4, "2026-04-04T11:00:00Z", {
        type: "observation",
        status: "error",
        input: '{"retry_failed": true}',
        output: '{"action": "abort"}',
        durationMs: 40,
        tokenUsage: undefined,
        error: {
          code: "SESSION_ABORTED",
          message: "Rate limit persists after retry. Aborting session.",
        },
      }),
    ],
  },

  // ── Session 5: Support bot FAQ generation (completed) ─────────────────────
  {
    id: "sess-005",
    agentName: "SupportBot",
    projectId: "proj-support",
    projectName: "Customer Support Bot",
    taskId: "task-005",
    taskName: "Generate FAQ from support tickets",
    startedAt: "2026-04-03T14:00:00Z",
    endedAt: "2026-04-03T14:03:20Z",
    status: "completed",
    totalSteps: 5,
    totalTokens: 15640,
    totalCostUsd: 0.0612,
    steps: [
      makeStep(1, "2026-04-03T14:00:00Z", {
        type: "tool_call",
        toolName: "query_database",
        input: '{"table": "support_tickets", "limit": 500, "status": "resolved"}',
        output: '{"rows": 500, "categories": ["billing", "shipping", "returns", "tech"]}',
        durationMs: 450,
        tokenUsage: undefined,
      }),
      makeStep(2, "2026-04-03T14:00:00Z", {
        type: "llm_call",
        input: '{"task": "cluster 500 tickets into FAQ topics", "ticket_count": 500}',
        output: '{"clusters": [{"topic": "refund_timeline", "count": 87}, {"topic": "tracking_link", "count": 64}]}',
        tokenUsage: { promptTokens: 6800, completionTokens: 1200, totalTokens: 8000 },
      }),
      makeStep(3, "2026-04-03T14:00:00Z", {
        type: "llm_call",
        input: '{"task": "draft FAQ answers for top 10 clusters"}',
        output: '{"faqs": [{"q": "How long do refunds take?", "a": "3-5 business days..."}]}',
        tokenUsage: { promptTokens: 3200, completionTokens: 1840, totalTokens: 5040 },
      }),
      makeStep(4, "2026-04-03T14:00:00Z", {
        type: "tool_call",
        toolName: "write_file",
        input: '{"path": "docs/faq.md", "content": "# FAQ\\n\\n..."}',
        output: '{"success": true, "bytes": 4820}',
        durationMs: 70,
        tokenUsage: undefined,
      }),
      makeStep(5, "2026-04-03T14:00:00Z", {
        type: "llm_call",
        input: '{"task": "summarize FAQ generation results"}',
        output: '{"summary": "Generated 10-item FAQ from 500 tickets. Top issue: refund timelines (17% of tickets)."}',
        tokenUsage: { promptTokens: 1200, completionTokens: 280, totalTokens: 1480 },
        durationMs: 1800,
      }),
    ],
  },

  // ── Session 6: Research agent web scraping with tool failure ──────────────
  {
    id: "sess-006",
    agentName: "ResearchAgent",
    projectId: "proj-research",
    projectName: "Research Assistant",
    taskId: "task-006",
    taskName: "Scrape competitor pricing data",
    startedAt: "2026-04-03T15:30:00Z",
    endedAt: "2026-04-03T15:32:10Z",
    status: "completed",
    totalSteps: 7,
    totalTokens: 6800,
    totalCostUsd: 0.0198,
    steps: [
      makeStep(1, "2026-04-03T15:30:00Z", {
        type: "llm_call",
        input: '{"task": "plan competitor pricing data collection strategy"}',
        output: '{"plan": ["scrape site A", "scrape site B", "compare pricing tiers"]}',
        tokenUsage: { promptTokens: 600, completionTokens: 180, totalTokens: 780 },
      }),
      makeStep(2, "2026-04-03T15:30:00Z", {
        type: "tool_call",
        toolName: "web_scrape",
        input: '{"url": "https://competitor-a.example.com/pricing"}',
        output: '{"html": "<div class=\\"pricing\\">...</div>", "status": 200}',
        durationMs: 2100,
        tokenUsage: undefined,
      }),
      makeStep(3, "2026-04-03T15:30:00Z", {
        type: "tool_call",
        toolName: "web_scrape",
        input: '{"url": "https://competitor-b.example.com/pricing"}',
        output: "",
        status: "error",
        durationMs: 10050,
        tokenUsage: undefined,
        error: {
          code: "TOOL_FAILURE",
          message: "HTTP 403 Forbidden: bot detection triggered on competitor-b.example.com",
        },
      }),
      makeStep(4, "2026-04-03T15:30:00Z", {
        type: "llm_call",
        input: '{"error": "TOOL_FAILURE", "url": "competitor-b", "task": "recover"}',
        output: '{"action": "use_cached_data", "source": "last_week_snapshot"}',
        tokenUsage: { promptTokens: 1100, completionTokens: 220, totalTokens: 1320 },
      }),
      makeStep(5, "2026-04-03T15:30:00Z", {
        type: "tool_call",
        toolName: "read_file",
        input: '{"path": "cache/competitor-b-2026-03-28.json"}',
        output: '{"data": {"starter": 29, "pro": 79, "enterprise": 299}}',
        durationMs: 50,
        tokenUsage: undefined,
      }),
      makeStep(6, "2026-04-03T15:30:00Z", {
        type: "llm_call",
        input: '{"task": "compare pricing tiers A vs B"}',
        output: '{"analysis": "Competitor A is 15% cheaper on starter tier, 8% more expensive on pro"}',
        tokenUsage: { promptTokens: 1800, completionTokens: 420, totalTokens: 2220 },
      }),
      makeStep(7, "2026-04-03T15:30:00Z", {
        type: "tool_call",
        toolName: "write_file",
        input: '{"path": "reports/competitor-pricing.md"}',
        output: '{"success": true}',
        durationMs: 60,
        tokenUsage: undefined,
      }),
    ],
  },

  // ── Session 7: E-commerce inventory timeout (failed) ──────────────────────
  {
    id: "sess-007",
    agentName: "CodeFixAgent",
    projectId: "proj-ecomm",
    projectName: "E-commerce AI",
    taskId: "task-007",
    taskName: "Fix inventory sync timeout",
    startedAt: "2026-04-02T16:00:00Z",
    endedAt: "2026-04-02T16:05:30Z",
    status: "failed",
    totalSteps: 4,
    totalTokens: 5600,
    totalCostUsd: 0.0162,
    steps: [
      makeStep(1, "2026-04-02T16:00:00Z", {
        type: "llm_call",
        input: '{"task": "diagnose inventory sync timeout error"}',
        output: '{"diagnosis": "ERP sync job running unbounded query on items table"}',
        tokenUsage: { promptTokens: 1200, completionTokens: 360, totalTokens: 1560 },
      }),
      makeStep(2, "2026-04-02T16:00:00Z", {
        type: "tool_call",
        toolName: "run_query",
        input: '{"sql": "EXPLAIN SELECT * FROM items WHERE updated_at > NOW() - INTERVAL 1 DAY"}',
        output: "",
        status: "error",
        durationMs: 30050,
        tokenUsage: undefined,
        error: {
          code: "QUERY_TIMEOUT",
          message: "Query execution timeout after 30s. Table items has 14M rows without index on updated_at.",
        },
      }),
      makeStep(3, "2026-04-02T16:00:00Z", {
        type: "llm_call",
        input: '{"error": "QUERY_TIMEOUT", "task": "propose index fix"}',
        output: '{"fix": "CREATE INDEX idx_items_updated_at ON items(updated_at)"}',
        tokenUsage: { promptTokens: 1800, completionTokens: 480, totalTokens: 2280 },
      }),
      makeStep(4, "2026-04-02T16:00:00Z", {
        type: "tool_call",
        toolName: "run_query",
        input: '{"sql": "CREATE INDEX idx_items_updated_at ON items(updated_at)"}',
        output: "",
        status: "error",
        durationMs: 30050,
        tokenUsage: undefined,
        error: {
          code: "QUERY_TIMEOUT",
          message: "Index creation timeout after 30s. Table locked by another process.",
        },
      }),
    ],
  },

  // ── Session 8: Support bot live agent handoff (completed) ─────────────────
  {
    id: "sess-008",
    agentName: "SupportBot",
    projectId: "proj-support",
    projectName: "Customer Support Bot",
    taskId: "task-008",
    taskName: "Escalation decision for VIP customer",
    startedAt: "2026-04-02T10:00:00Z",
    endedAt: "2026-04-02T10:01:48Z",
    status: "completed",
    totalSteps: 5,
    totalTokens: 4960,
    totalCostUsd: 0.0148,
    steps: [
      makeStep(1, "2026-04-02T10:00:00Z", {
        type: "retrieval",
        toolName: "vector_search",
        input: '{"query": "VIP customer angry about missing order", "k": 5}',
        output: '{"chunks": [{"text": "VIP escalation policy: immediate human handoff..."}]}',
        durationMs: 280,
        tokenUsage: undefined,
      }),
      makeStep(2, "2026-04-02T10:00:00Z", {
        type: "tool_call",
        toolName: "query_database",
        input: '{"query": "SELECT tier, ltv FROM customers WHERE id = ?", "params": ["cust-vip-9821"]}',
        output: '{"tier": "platinum", "ltv": 48200}',
        durationMs: 120,
        tokenUsage: undefined,
      }),
      makeStep(3, "2026-04-02T10:00:00Z", {
        type: "llm_call",
        input: '{"customer_tier": "platinum", "issue": "missing_order", "policy": "immediate_escalation"}',
        output: '{"decision": "escalate_to_human", "priority": "high", "assign_to": "vip-team"}',
        tokenUsage: { promptTokens: 1600, completionTokens: 280, totalTokens: 1880 },
      }),
      makeStep(4, "2026-04-02T10:00:00Z", {
        type: "action",
        toolName: "create_ticket",
        input: '{"priority": "high", "team": "vip-team", "customer_id": "cust-vip-9821"}',
        output: '{"ticket_id": "TKT-88821", "assigned_to": "sarah.k@company.com"}',
        durationMs: 200,
        tokenUsage: undefined,
      }),
      makeStep(5, "2026-04-02T10:00:00Z", {
        type: "llm_call",
        input: '{"task": "draft escalation summary for human agent"}',
        output: '{"summary": "Platinum customer (LTV $48.2K) reporting missing order. Escalated to VIP team. Ticket TKT-88821 assigned to Sarah K."}',
        tokenUsage: { promptTokens: 1800, completionTokens: 1280, totalTokens: 3080 },
      }),
    ],
  },
]
